/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Windows;

import Eventos.RecorridoGrafico;
import Logica.DatosGlobales;
import Logica.Motocicleta;
import Logica.Pedido;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar
 */
public class VtnEstadoEntregas extends javax.swing.JFrame {

    DatosGlobales datosGlobales = DatosGlobales.getInstance();
    ArrayList<Pedido> pedidos;
    
    public VtnEstadoEntregas() {
        this.pedidos = datosGlobales.getPEDIDOS();
        
        
        initComponents();
        
        ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/moto.jpg"));
        Image imagenOriginal = iconoOriginal.getImage();
        Image imagenRedimension = imagenOriginal.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        
        ImageIcon imagenRedimensionada = new ImageIcon(imagenRedimension);
        moto1.setIcon(imagenRedimensionada);
        moto2.setIcon(imagenRedimensionada);
        moto3.setIcon(imagenRedimensionada);
        
        pnlEscenario.revalidate();
        pnlEscenario.repaint();
    }
    private void enviarMoto(String motoNombre, JLabel motoLabel) {
    Pedido pedido = new Pedido();
    boolean pedidoEncontrado = false;
    
    for (Pedido pedidoBus : datosGlobales.getPEDIDOS()) {
        if (pedidoBus.getVehiculoName().equals(motoNombre) && !pedidoBus.isPedidoFinalizado()) {
            pedido = pedidoBus;
            motoLabel.setLocation(37, motoLabel.getLocation().y);
            RecorridoGrafico recorrido = new RecorridoGrafico(motoLabel, this, pedidoBus);
            recorrido.start();
            pedidoEncontrado = true;
            break;
        }
    }
    
    if (!pedidoEncontrado) {
        JOptionPane.showMessageDialog(this, "No hay ningún pedido asociado a esta moto"+" "+motoNombre);
    }
}
    public JLabel getMeta() {
        return meta;
    }

    public void setMeta(JLabel meta) {
        this.meta = meta;
    }

    public JLabel getMoto1() {
        return moto1;
    }

    public void setMoto1(JLabel moto1) {
        this.moto1 = moto1;
    }

    public JLabel getMoto2() {
        return moto2;
    }

    public void setMoto2(JLabel moto2) {
        this.moto2 = moto2;
    }

    public JLabel getMoto3() {
        return moto3;
    }

    public void setMoto3(JLabel moto3) {
        this.moto3 = moto3;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlEventoMotos = new javax.swing.JPanel();
        pnlEscenario = new javax.swing.JPanel();
        btnEnviarMoto1 = new javax.swing.JButton();
        moto1 = new javax.swing.JLabel();
        moto2 = new javax.swing.JLabel();
        btnEnviarSegundaMoto = new javax.swing.JButton();
        moto3 = new javax.swing.JLabel();
        btnEnviarTerceraMoto = new javax.swing.JButton();
        meta = new javax.swing.JLabel();
        btnEnviarTodos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnEnviarMoto1.setText("enviar");
        btnEnviarMoto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMoto1ActionPerformed(evt);
            }
        });

        btnEnviarSegundaMoto.setText("enviar");
        btnEnviarSegundaMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarSegundaMotoActionPerformed(evt);
            }
        });

        btnEnviarTerceraMoto.setText("enviar");
        btnEnviarTerceraMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarTerceraMotoActionPerformed(evt);
            }
        });

        meta.setText("jLabel1");

        javax.swing.GroupLayout pnlEscenarioLayout = new javax.swing.GroupLayout(pnlEscenario);
        pnlEscenario.setLayout(pnlEscenarioLayout);
        pnlEscenarioLayout.setHorizontalGroup(
            pnlEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEscenarioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnviarTerceraMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnviarSegundaMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnviarMoto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 753, Short.MAX_VALUE)
                .addComponent(meta)
                .addGap(28, 28, 28))
        );
        pnlEscenarioLayout.setVerticalGroup(
            pnlEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEscenarioLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(moto1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviarMoto1)
                .addGap(38, 38, 38)
                .addComponent(moto2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviarSegundaMoto)
                .addGap(26, 26, 26)
                .addComponent(moto3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnEnviarTerceraMoto)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(pnlEscenarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(meta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnEnviarTodos.setText("Enviar Todos");
        btnEnviarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarTodosActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEventoMotosLayout = new javax.swing.GroupLayout(pnlEventoMotos);
        pnlEventoMotos.setLayout(pnlEventoMotosLayout);
        pnlEventoMotosLayout.setHorizontalGroup(
            pnlEventoMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventoMotosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEventoMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlEventoMotosLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlEventoMotosLayout.setVerticalGroup(
            pnlEventoMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventoMotosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEventoMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnEnviarTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEscenario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEventoMotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pnlEventoMotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarMoto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMoto1ActionPerformed
        
        enviarMoto("motocicleta1", moto1);
        
    }//GEN-LAST:event_btnEnviarMoto1ActionPerformed

    private void btnEnviarSegundaMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarSegundaMotoActionPerformed
        enviarMoto("motocicleta2", moto2);
    }//GEN-LAST:event_btnEnviarSegundaMotoActionPerformed

    private void btnEnviarTerceraMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarTerceraMotoActionPerformed
       enviarMoto("motocicleta3", moto3);
    }//GEN-LAST:event_btnEnviarTerceraMotoActionPerformed

    private void btnEnviarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarTodosActionPerformed
       enviarMoto("motocicleta1", moto1);
       enviarMoto("motocicleta2", moto2);
       enviarMoto("motocicleta3", moto3);
    }//GEN-LAST:event_btnEnviarTodosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarMoto1;
    private javax.swing.JButton btnEnviarSegundaMoto;
    private javax.swing.JButton btnEnviarTerceraMoto;
    private javax.swing.JButton btnEnviarTodos;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel meta;
    private javax.swing.JLabel moto1;
    private javax.swing.JLabel moto2;
    private javax.swing.JLabel moto3;
    private javax.swing.JPanel pnlEscenario;
    private javax.swing.JPanel pnlEventoMotos;
    // End of variables declaration//GEN-END:variables
}
