/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Windows;

/**
 *
 * @author cesar
 */
public class VtnOpcionesAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VtnOpcionesAdmin
     */
    public VtnOpcionesAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRealizarPedidos = new javax.swing.JButton();
        btnVerEstadoEnvios = new javax.swing.JButton();
        btnReportesEntregas = new javax.swing.JButton();
        btnAgregarNuevosProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnRealizarPedidos.setText("realizar pedidos");
        btnRealizarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPedidosActionPerformed(evt);
            }
        });

        btnVerEstadoEnvios.setText("ver estado de envios");
        btnVerEstadoEnvios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstadoEnviosActionPerformed(evt);
            }
        });

        btnReportesEntregas.setText("Reportes entregas");
        btnReportesEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesEntregasActionPerformed(evt);
            }
        });

        btnAgregarNuevosProd.setText("Agregar Nuevos Productos");
        btnAgregarNuevosProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNuevosProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRealizarPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarNuevosProd, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                            .addComponent(btnVerEstadoEnvios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReportesEntregas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnAgregarNuevosProd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRealizarPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerEstadoEnvios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportesEntregas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPedidosActionPerformed
        VtnRealizarPedidos vtnRealizarPedidos = new VtnRealizarPedidos();
        vtnRealizarPedidos.setVisible(true);
        vtnRealizarPedidos.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRealizarPedidosActionPerformed

    private void btnVerEstadoEnviosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstadoEnviosActionPerformed
        VtnEstadoEntregas vtnEstadoEntregas = new VtnEstadoEntregas();
        vtnEstadoEntregas.setVisible(true);
        vtnEstadoEntregas.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVerEstadoEnviosActionPerformed

    private void btnReportesEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesEntregasActionPerformed
        VtnRegistroEntregas vtnRegistroEntregas = new VtnRegistroEntregas();
        vtnRegistroEntregas.setVisible(true);
        vtnRegistroEntregas.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnReportesEntregasActionPerformed

    private void btnAgregarNuevosProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNuevosProdActionPerformed
        VtnAgregarProductos vtnAgregarProductos  = new VtnAgregarProductos();
        vtnAgregarProductos.setVisible(true);
        vtnAgregarProductos.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAgregarNuevosProdActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNuevosProd;
    private javax.swing.JButton btnRealizarPedidos;
    private javax.swing.JButton btnReportesEntregas;
    private javax.swing.JButton btnVerEstadoEnvios;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
