/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Windows;

import Logica.DatosGlobales;
import Logica.Motocicleta;
import Logica.Pedido;
import Logica.Producto;
import TableModels.PedidoTableModel;
import TableModels.ProductosTableModel;
import java.time.Instant;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar
 */
public class VtnRealizarPedidos extends javax.swing.JFrame {
    DatosGlobales datosGlobales = DatosGlobales.getInstance();
    ProductosTableModel productosTableModel = new ProductosTableModel();
    PedidoTableModel pedidoTableModel;
    Pedido pedido;
    
    
    
    public VtnRealizarPedidos() {
        pedido = new Pedido();
        pedidoTableModel = new PedidoTableModel(pedido);
        datosGlobales.agregarPedido(pedido);
        initComponents();

        actualizarCbb();
    }
    public void actualizarCbb (){
        for(Motocicleta motocicleta : datosGlobales.getMOTOCICLETAS()){
            if(!motocicleta.isMotoOcupada()){
                
                cbbMotocicletas.addItem(motocicleta.getNombre());
            }
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductosCompra = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarAlPedido = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbbMotocicletas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDistanciaARecorrer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnConfirmarPedido = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblProductosCompra.setModel(productosTableModel);
        jScrollPane1.setViewportView(tblProductosCompra);

        jLabel1.setText("PRODUCTOS");

        tblPedido.setModel(pedidoTableModel);
        jScrollPane2.setViewportView(tblPedido);

        jLabel2.setText("PEDIDO");

        btnAgregarAlPedido.setText("Agregar Productos al pedido");
        btnAgregarAlPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlPedidoActionPerformed(evt);
            }
        });

        jLabel3.setText("VEHICULO");

        jLabel4.setText("DISTANCIA A RECORRER");

        jLabel5.setText("Km");

        jLabel6.setText("Total:");

        lblTotal.setText("jLabel7");

        btnConfirmarPedido.setText("Confirmar pedido");
        btnConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(btnAgregarAlPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbMotocicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDistanciaARecorrer, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConfirmarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarAlPedido))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbMotocicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDistanciaARecorrer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnConfirmarPedido))
                .addGap(37, 37, 37))
        );

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAlPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlPedidoActionPerformed
        int filaSelec = tblProductosCompra.getSelectedRow();
        
        if(filaSelec != -1){
            Producto producto = datosGlobales.getPRODUCTOS().get(filaSelec);
            double precioProd = Double.parseDouble(producto.getPrecio());
            pedidoTableModel.agregarProductoAlPedido(producto);
            pedido.actualizarTotal(precioProd);
            lblTotal.setText(Double.toString(pedido.getTotal()));
        }
        else{
            JOptionPane.showMessageDialog(this, "debe seleccionar un producto de la tabla");
        }
    }//GEN-LAST:event_btnAgregarAlPedidoActionPerformed

    private void btnConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPedidoActionPerformed
            
         if (!pedido.isMotoAsignada()) {

            if (tblPedido.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "se deben agregar productos para hacer el pedido");
            } else {
                if (!txtDistanciaARecorrer.getText().isEmpty()) {

                    try {
                        int distancia = Integer.parseInt(txtDistanciaARecorrer.getText());

                        if (distancia <= 10 && distancia >= 1) {
                            String motocicleta = (String) cbbMotocicletas.getSelectedItem();
                            cbbMotocicletas.removeItem(motocicleta);
                            pedido.setVehiculoName(motocicleta);
                            pedido.asignarMoto();
                            pedido.setDistancia(txtDistanciaARecorrer.getText());
                            Date horaEmision = new Date();
                            pedido.setHoraPartida(horaEmision);
                            System.out.println(horaEmision);
                            for(Motocicleta motocicletaBus : datosGlobales.getMOTOCICLETAS()){
                                if(motocicletaBus.getNombre().equals(motocicleta)){
                                    motocicletaBus.setPedido(pedido);
                                    motocicletaBus.ocuparMoto();
                                    break;
                                
                                }
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "la distancia debe ser mayor o igual a 1, menor o igual que 10");
                        }

                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "la distancia debe ser un numero");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "debe colocar una distancia");
                }
            }
        }
         else{
             JOptionPane.showMessageDialog(this, "ya se ha confirmado el pedido, no se puede modificar");
         }
            
    }//GEN-LAST:event_btnConfirmarPedidoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlPedido;
    private javax.swing.JButton btnConfirmarPedido;
    private javax.swing.JComboBox<String> cbbMotocicletas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblPedido;
    private javax.swing.JTable tblProductosCompra;
    private javax.swing.JTextField txtDistanciaARecorrer;
    // End of variables declaration//GEN-END:variables
}
